### ISSUE TITLE
I want to creat the menu like app of path on ios . left menu and right menu

### ISSUE THREAD

**Issue by liufsd** [adamrocker/simple-side-drawer#1]
Hey 

First of all, thanks for sharing your app menu drawer implementation.

OK. I want to creat the menu like app of path on ios . that have two menu for left and right in the mainactiviy in the theam time.

But in your code,This is currently not possible,  you just have only one for  left menu.

how to do that ?

Thanks.

**Comment by adamrocker** [comment]
Thank you for the request. 
The purpose of this library is to provide the slide menu easily so the left side menu is not available now.
I will try to implement the right slide menu some how :)
Thank you!

**Comment by liufsd** [comment]
Ok!call me if you get it !Thanks a lot!

**Comment by adamrocker** [comment]
I updated it and you can use right-side menu :)

**Comment by liufsd** [comment]
Thanks a lot.
