### ISSUE TITLE
java.lang.IllegalStateException on setBehindContentView

### ISSUE THREAD

**Issue by aTakeshiKominato** [adamrocker/simple-side-drawer#2]
Following exception was thrown when mAboveView.addView(above) called on setBehindContentView() method.

01-27 20:55:25.222: W/System.err(5964): Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
01-27 20:55:25.226: W/System.err(5964):     at android.view.ViewGroup.addViewInner(ViewGroup.java:3337)
01-27 20:55:25.226: W/System.err(5964):     at android.view.ViewGroup.addView(ViewGroup.java:3208)
01-27 20:55:25.250: W/System.err(5964):     at android.view.ViewGroup.addView(ViewGroup.java:3165)
01-27 20:55:25.250: W/System.err(5964):     at android.view.ViewGroup.addView(ViewGroup.java:3145)
01-27 20:55:25.250: W/System.err(5964):     at com.navdrawer.SimpleSideDrawer.setBehindContentView(SimpleSideDrawer.java:137)

This error does not occur on demo example application. I don't know why.
Anyway, it seems that the modification of SimpleSideDrawer.java on commit e066e1eea7 is not needed because mAboveView was completely prepared on constructor.
It works well if I erase the modification.

Thank you for your useful OSS.

**Comment by adamrocker** [comment]
Thank you for your report.
This exception might be thrown when the child's View has already its parent View so I also do not know why this happened.
So could you please make a minimum source code to reproduce this exception?
I'd like to check and fixed this bug with flexible logic.
Thank you.

**Comment by aTakeshiKominato** [comment]
sorry for my late reply.

You remove Library(SimpleSideDrawer0.0.1.jar) from your demo project and add source code(SimpleSideDrawer.java) instead,
and you can reproduce the problem.

**Comment by h3r3x3** [comment]
Remove some code, then it's ok, please fix it.

```
public View setBehindContentView(int behindLayout) {
    mBehindView.removeAllViews();
    View content = ((LayoutInflater) getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(behindLayout, mBehindView);
    mPaddingRect = new Rect(content.getPaddingLeft(), content.getPaddingTop(), content.getPaddingRight(), content.getPaddingBottom());
    //mBehindViewContent = act.getLayoutInflater().inflate(behindLayout, mBehindView);
    return content;
}
```

**Comment by adamrocker** [comment]
Thank you! I fixed this bug and published the new version. Please check it out :)
